// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrCwy4-xBlRryFZN0uJkjAMtnZWadRXEI',
    appId: '1:1045818619340:web:ed49ce517b5fff2a859969',
    messagingSenderId: '1045818619340',
    projectId: 'chatapp-e404f',
    authDomain: 'chatapp-e404f.firebaseapp.com',
    storageBucket: 'chatapp-e404f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCXF0yRYjOQakQp2X3i9MyzZo65F01nRM',
    appId: '1:1045818619340:android:de7310e143767642859969',
    messagingSenderId: '1045818619340',
    projectId: 'chatapp-e404f',
    storageBucket: 'chatapp-e404f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1B6_8ilTDrGoxG842IgtDmqjzSa7vqrA',
    appId: '1:1045818619340:ios:46fad95a85f50003859969',
    messagingSenderId: '1045818619340',
    projectId: 'chatapp-e404f',
    storageBucket: 'chatapp-e404f.appspot.com',
    iosClientId: '1045818619340-dollhvjp815n2fjlntrgamhhfqh8geqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1B6_8ilTDrGoxG842IgtDmqjzSa7vqrA',
    appId: '1:1045818619340:ios:46fad95a85f50003859969',
    messagingSenderId: '1045818619340',
    projectId: 'chatapp-e404f',
    storageBucket: 'chatapp-e404f.appspot.com',
    iosClientId: '1045818619340-dollhvjp815n2fjlntrgamhhfqh8geqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
